
source("QueueModule.R") # Make sure to change directory accordingly 
library(testthat)

test_that("first_tests", {
  q <- create_queue(4)
  prnt_queue(q)
  expect_equal(get_queue_size(q), 0)
  q <- enqueue(q, 2)
  prnt_queue(q)
  expect_equal(get_queue_size(q), 1)
  expect_equal(peek(q), 2)
  q <- pop(q)
  expect_equal(get_queue_size(q), 0)
  expect_equal(peek(q), NULL)
  q <- enqueue(q, 7)
  q <- enqueue(q, 123)
  q <- enqueue(q, 1351234)
  expect_equal(get_queue_size(q), 3)
  q <- enqueue(q, 1)
  expect_equal(get_queue_size(q), 4)
  q <- enqueue(q, 10)
  expect_equal(get_queue_size(q), 4)
  prnt_queue(q)
})

test_that("Second_tests", {
    q <- create_queue(2)
    expect_equal(peek(q), NULL)
    q <- enqueue(q, 2)
    cat("line ", 32, ": ", sep = "", end = " ")
    prnt_queue(q)
    expect_equal(get_queue_size(q), 1)
    q <- enqueue(q, 2000)
    cat("line: ", 36, ": ", sep = "", end = " ")
    prnt_queue(q)
    expect_equal(get_queue_size(q), 2)
    q <- enqueue(q, 3000)
    expect_equal(get_queue_size(q), 2)
    cat("line: ", 41, ": ", sep = "", end = " ")
    prnt_queue(q)
    q <- pop(q)
    q <- pop(q)
    expect_equal(get_queue_size(q), 0)
    cat("line: ", 46, ": ", sep = "", end = " ")
    prnt_queue(q)
    q <- pop(q)
    q <- pop(q)
    q <- pop(q)
    cat("line: ", 51, ": ", sep = "", end = " ")
    prnt_queue(q)
    q <- enqueue(q, 22)
    cat("line: ", 54, ": ", sep = "", end = " ")
    prnt_queue(q)
    expect_equal(get_queue_size(q), 1)
    q <- enqueue(q, 32)
    cat("line: ", 58, ": ", sep = "", end = " ")
    prnt_queue(q)
    expect_equal(get_queue_size(q), 2)
    q <- enqueue(q, 32)
})
